### ISSUE TITLE
Is there some reference paper

### ISSUE THREAD

**Issue by narutojxl** [CentroEPiaggio/lidar_based_map_updating#1]
Hello, is there some reference paper, thanks for your help.

**Comment by tenvinc** [comment]
I recently came across this paper on IROS 2022, and the paper referred to this GitHub link. I think that should be the reference paper, you can find it under "Efficient 2D LIDAR-Based Map Updating For Long-Term Operations in Dynamic Environments"

**Comment by narutojxl** [comment]
Thanks for your help :)
